DROP DATABASE customer_behavior;
GO

USE customer_behavior;

SELECT TOP 10 * FROM cleaned_table;

------------------------------------------------------------------------------------------------------------------------------------
----Q1. What is the total revenue generated by male vs. female customers?

SELECT gender, SUM( [ purchase_amount] )AS revenue
FROM cleaned_table
GROUP BY gender;

------Q2. Which customers used a discount but still spent more than the average purchase amount? 

SELECT customer_id, discount_applied
FROM cleaned_table
WHERE discount_applied  = 'Yes' AND purchase_amount >=  AVG(purchase_amount)  FROM cleaned_table)


-----Q3. Which are the top 5 products with the highest average review rating?


SELECT TOP 5 item_purchased, ROUND(AVG(CAST(review_rating AS FLOAT)), 2) AS "Average Product Rating"
FROM cleaned_table
GROUP BY item_purchased
ORDER BY AVG(CAST(review_rating AS FLOAT)) DESC;



---Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

SELECT 
    shipping_type, 
    ROUND(AVG(CAST(purchase_amount AS FLOAT)), 2) AS avg_purchase_amount
FROM cleaned_table
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;




















SELECT COLUMN_NAME 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'cleaned_table';